# Generated by Django 3.2.8 on 2022-11-02 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('cod_album', models.IntegerField(verbose_name='cod_album')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('cant_temas', models.IntegerField(verbose_name='cant_temas')),
                ('fec_lanzamiento', models.DateField(verbose_name='fec_lanzamiento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='precio')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('caratula', models.ImageField(null=True, upload_to='imagenes/', verbose_name='caratula')),
            ],
        ),
        migrations.CreateModel(
            name='Discografica',
            fields=[
                ('id_discografica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id_formato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('id_interprete', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('duracion', models.TimeField(verbose_name='duracion')),
                ('autor', models.CharField(max_length=50, verbose_name='autor')),
                ('compositor', models.CharField(max_length=50, verbose_name='compositor')),
                ('cod_album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disqueria.album')),
                ('id_interprete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disqueria.interprete')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='id_discografica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disqueria.discografica'),
        ),
        migrations.AddField(
            model_name='album',
            name='id_formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disqueria.formato'),
        ),
        migrations.AddField(
            model_name='album',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disqueria.genero'),
        ),
        migrations.AddField(
            model_name='album',
            name='id_interprete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disqueria.interprete'),
        ),
    ]
