# Generated by Django 3.2.8 on 2022-11-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disqueria', '0002_auto_20221106_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='caratula',
            field=models.FileField(default='imagenes/caratula.jpg', null=True, upload_to='imagenes/', verbose_name='Carátula'),
        ),
    ]
