# Generated by Django 3.2.8 on 2022-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disqueria', '0003_alter_album_caratula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='caratula',
            field=models.ImageField(default='imagenes/caratula.jpg', null=True, upload_to='imagenes/', verbose_name='Carátula'),
        ),
    ]
